### ISSUE TITLE
Release conflict

### ISSUE THREAD

**Issue by fpronto** [tristanls/dynamodb-lock-client#21] opened 2019-12-08 23:19 UTC
Hi again, having troubles again
I'm using the FailOpen feature
if i try to do a release at same time of an heartbeat, it crashes
i think this happens because the lock try to release with a diferent guid value

- heartbeat reach the database
- release reach the database before heartbeat return and change guid value in the lock

i was able to reproduce this error because my middleware have a some delay
we are doing a workarround by checking the time
if it's close to an heartbeat wait a bit to release

**Comment by tristanls** [comment] 2019-12-09 03:25
Hello @fpronto ,

Could you elaborate what you mean by a crash? Is there a stack trace that points to where the crash initiates from?

Without knowing the details, the one thing that comes to mind is that there is one expected way the module can crash during normal operation. The last sentence of the [client.acquireLock(id, callback)](https://github.com/tristanls/dynamodb-lock-client#clientacquirelockid-callback) section states:
> ...if `heartbeatPeriodMs` option is specified, lock may emit an `error` event if it fails a heartbeat operation.

That implies if you do not register an error handler on `lock`:
```javascript
lock.on("error", error => console.error(error));
```
and an error occurs, the normal [Node.js error propegation happens](https://nodejs.org/api/errors.html#errors_error_propagation_and_interception) resulting in:
> For all EventEmitter objects, if an 'error' event handler is not provided, the error will be thrown, causing the Node.js process to report an uncaught exception and crash unless either: The domain module is used appropriately or a handler has been registered for the 'uncaughtException' event. 

Again, I'm just guessing, a stack trace would help orient me to where the problem is occuring.

**Comment by fpronto** [comment] 2019-12-09 11:59
I can't show you the error stack right now
let me try to re-explain the problem.
It's not a crash, it's a 'malfunction'
- Context:

I can't use the aws.Dynamodb.DocumentClient in my app because i'm creating a front-end app (and i'm worried about exposing apiKeys and accessTokens)
So, the workarround is recreating every request you need in the package in a REST way (maybe there is a better solution but it's the one that we are using right now), there is a delay in every request.
- Problem:

If i try to do a release (activated by a user) after the heartbeart request lauchs and before it returns, the release crashs because it thinks another user had catch this lock.
This error is not catchable in the way that you have said, just because it's not an heartbeat error, its a release error

- Possible Solution

  - If the release function is aware of the heartbeat, it will wait if the heartbeat request is sended
  - Can't do a release if the heartbeat doesn't return

Thanks for your time, and if you couldn't understand i will try to reproduce the error (it's realy hard to reproduce right now)

**Comment by tristanls** [comment] 2019-12-10 03:31
Ok. I think I'm maybe understanding a bit more.

It should not matter which request is in progress (heartbeat or release) because DynamoDB behaves as if the request is atomic. As such, there is one other place, inside fail open lock release code, where a request can fail. This isn't apparent because this error is expected and accounted for within the module. However, if you are replacing the DocumentClient, then perhaps you're not providing the expected error?

[Lock.prototype._releaseFailOpen](https://github.com/tristanls/dynamodb-lock-client/blob/master/index.js#L476) can observe `ConditionalCheckFailedException`, which would also be part of normal operation. I would expect `ConditionalCheckFailedException` if the heartbeat updated the `guid` before `_releaseFailOpen` reached DynamoDB.

If the `guid` is not what is expected, when `_releaseFailOpen` is called, then the correct behavior when observing `ConditionalCheckFailedException` is to succeed (the heartbeat should have been stopped as part of lock release logic already). Eventually, the lock will be released when the `leaseDurationMs` elapses.

**Comment by fpronto** [comment] 2019-12-10 11:48
when I'm refering to a request, it's a http request (I'm think that maybe some operations can happen in an unexpected order, i'm wrong?)
I understand what you are saying and its a correct way for most cases

when i try to release, the heartbeat is stoped, but what stays in dynamodb is an open lock

this is not a error in code, is a malfunction because of the delays
i will try to reproduce the error later today, i'm having troubles to explain this

**Comment by fpronto** [comment] 2019-12-10 11:59
> [Lock.prototype._releaseFailOpen](https://github.com/tristanls/dynamodb-lock-client/blob/master/index.js#L476) can observe `ConditionalCheckFailedException`, which would also be part of normal operation. I would expect `ConditionalCheckFailedException` if the heartbeat updated the `guid` before `_releaseFailOpen` reached DynamoDB.
> 

We were having this malfunction with only one user, and were getting this error when releasing.
ConditionalCheckFailedException should only be a for when other user get the lock right?

Even if its one user using the lock will stay open? if that's the expected behavior we don't have troubles.
But if you have a bigger lease time the next user that try to get the lock will wait to much time without need

Thanks for your help

**Comment by tristanls** [comment] 2019-12-10 12:12
> We were having this malfunction with only one user, and were getting this error when releasing.
> ConditionalCheckFailedException should only be a for when other user get the lock right?

You could observe this even with a single user. This is because [heartbeat changes the `guid` every time](https://github.com/tristanls/dynamodb-lock-client/blob/master/index.js#L353). 

You're correct that a bigger lease time leads to next user having to wait longer.

I think that once #22 is addressed, you'll be able to retry the release without having to wait the full lease time. However, currently, due to #22, retrying release is unsafe.

**Comment by tristanls** [comment] 2019-12-11 00:02
With the release of [v0.6.2](https://github.com/tristanls/dynamodb-lock-client/releases/tag/v0.6.2) it should now be safe for you to retry `lock.release()` if you do not wish to wait for full lease duration.

**Comment by tristanls** [comment] 2019-12-11 00:08
My previous statement that it was unsafe to retry `lock.release()` for a fail open lock was incorrect. The unsafe condition only occured if `heartbeatTimeoutMs` was not provided for `FailOpen` lock, in which case, `lock.release()` would execute `FailClosed` release protocol. If `heartbeatTimeoutMs` was provided for `FailOpen` lock, retrying `lock.release()` was safe all along.

**Comment by fpronto** [comment] 2019-12-13 14:49
A sugestion, semi-related to this issue.
have you considered the TTL feature from dynamodb to help dealing with the failing release?
TTL being 2times the leasing time for example

**Comment by tristanls** [comment] 2019-12-13 15:36
> Important
> 
> DynamoDB typically deletes expired items within 48 hours of expiration. The exact duration within which an item truly gets deleted after expiration is specific to the nature of the workload and the size of the table. Items that have expired and have not been deleted still appear in reads, queries, and scans. These items can still be updated, and successful updates to change or remove the expiration attribute are honored.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/howitworks-ttl.html

**Closed** 2020-05-26 13:45 UTC

**Comment by DASPRiD** [comment] 2023-04-03 13:00
@tristanls it's still a good additional choice though for cleaning up abandoned items.
